### ISSUE TITLE
Questions about the different distance resolutions between MUSIC and 3D-FFT

### ISSUE THREAD

**Issue by StZhang-B** [ekurtgl/FMCW-MIMO-Radar-Simulation#1]
Because both MUSIC and 3D-FFT use 2D-FFT to measure distance, then why are the distance resolutions of the two different?

**Comment by ekurtgl** [comment]
MUSIC is a subspace-based method, it is not using FFT (see [here](https://www.mathworks.com/help/phased/ug/music-super-resolution-doa-estimation.html) . We use FFT in range estimation while MUSIC is used in angle estimation. I hope this helps.

**Comment by StZhang-B** [comment]
That's helpful, thank you.

**Comment by ekurtgl** [comment]
You are welcome!
