### ISSUE TITLE
FMCW_sim_v3.m file

### ISSUE THREAD

**Issue by 123456ZF** [ekurtgl/FMCW-MIMO-Radar-Simulation#2]
Hello, in your FMCW_sim_v3.m file, this skel_hist function is undefined，

**Comment by ekurtgl** [comment]
Hi @123456ZF ,

It is not a function, it is a variable in the `[20220817_191142_00.mat](https://github.com/ekurtgl/FMCW-MIMO-Radar-Simulation/blob/main/20220817_191142_00.mat)` file. Make sure you can load. I hope this helps.

**Comment by 123456ZF** [comment]
@ekurtgl Thank you for your answer

**Comment by ekurtgl** [comment]
You are welcome!
