### ISSUE TITLE
Cartesian to Polar Distortion towards the FOV edges

### ISSUE THREAD

**Issue by DenizEDRS** [ekurtgl/FMCW-MIMO-Radar-Simulation#4]
Hi,
im currently working on a similar program. The issue i am encountering is that artificially created Range-Angle Heatmaps are not fully accurate. In your animation at the very bottom you seem to have a distortion that occurs towards your angular edges, do you know how those are describable to be reproduced?

**Comment by ekurtgl** [comment]
Hi,

It is an expected phenomenon as the approaches closer to the radar, its body parts will allocate more bins in the angular spectrum. You can think of a small rubik cube example. If the cubical object is at 0.1 m away from the radar, its return signals can allocate the angular intervals of -45 to 45 degrees, but when it is 5 m away, it might be detected only at -5 to 5 degrees. We observe a similar phenomenon here. So, it is not a distortion, but an expected outcome. I hope this helps.

**Comment by DenizEDRS** [comment]
thank you for the quick answer,
i am now able to replicate radar heatmap generations, the issue was due to range clipping in my own code that wasnt fully adjusted.
